# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageSettingsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(535, 878)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 515, 858))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 32, 0, 1, 2)
        self.groupBox_utilities = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_utilities.setObjectName("groupBox_utilities")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_utilities)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_ruler_value = QtWidgets.QLabel(self.groupBox_utilities)
        self.label_ruler_value.setText("")
        self.label_ruler_value.setObjectName("label_ruler_value")
        self.gridLayout_6.addWidget(self.label_ruler_value, 1, 0, 1, 3)
        self.pushButton_show_alignment_area = QtWidgets.QPushButton(self.groupBox_utilities)
        self.pushButton_show_alignment_area.setObjectName("pushButton_show_alignment_area")
        self.gridLayout_6.addWidget(self.pushButton_show_alignment_area, 2, 0, 1, 3)
        self.checkBox_enable_ruler = QtWidgets.QCheckBox(self.groupBox_utilities)
        self.checkBox_enable_ruler.setObjectName("checkBox_enable_ruler")
        self.gridLayout_6.addWidget(self.checkBox_enable_ruler, 0, 2, 1, 1)
        self.scalebar_checkbox = QtWidgets.QCheckBox(self.groupBox_utilities)
        self.scalebar_checkbox.setObjectName("scalebar_checkbox")
        self.gridLayout_6.addWidget(self.scalebar_checkbox, 0, 0, 1, 1)
        self.crosshair_checkbox = QtWidgets.QCheckBox(self.groupBox_utilities)
        self.crosshair_checkbox.setChecked(True)
        self.crosshair_checkbox.setObjectName("crosshair_checkbox")
        self.gridLayout_6.addWidget(self.crosshair_checkbox, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_utilities, 29, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_utilities.setTitle(_translate("Form", "Utilities"))
        self.pushButton_show_alignment_area.setText(_translate("Form", "Show Alignment Area"))
        self.checkBox_enable_ruler.setText(_translate("Form", "Ruler "))
        self.scalebar_checkbox.setText(_translate("Form", "Scale Bar"))
        self.crosshair_checkbox.setText(_translate("Form", "Cross Hair"))
