from fibsem.config import (
    AUTOLAMELLA_BASE_PATH as BASE_PATH,
    AUTOLAMELLA_CONFIG_PATH as CONFIG_PATH,
    AUTOLAMELLA_LOG_PATH as LOG_PATH,
    AUTOLAMELLA_PROTOCOL_PATH as PROTOCOL_PATH,
    AUTOLAMELLA_TASK_PROTOCOL_PATH as TASK_PROTOCOL_PATH,
    FEATURE_COINCIDENCE_MILLING_ENABLED,
    AUTOLAMELLA_EXPERIMENT_NAME as EXPERIMENT_NAME,
)
