from fibsem.config import (
    AUTOLAMELLA_BASE_PATH as BASE_PATH,
    AUTOLAMELLA_CONFIG_PATH as CONFIG_PATH,
    AUTOLAMELLA_LOG_PATH as LOG_PATH,
    AUTOLAMELLA_PROTOCOL_PATH as PROTOCOL_PATH,
    AUTOLAMELLA_TASK_PROTOCOL_PATH as TASK_PROTOCOL_PATH,
)

EXPERIMENT_NAME = "AutoLamella"

####### FEATURE FLAGS
FEATURE_MINIMAP_PLOT_WIDGET_ENABLED = True
FEATURE_LAMELLA_POSITION_ON_LIVE_VIEW_ENABLED = False
FEATURE_POSE_CONTROLS_ENABLED = False
FEATURE_DISPLAY_GRID_CENTER_MARKER = False
